### PR TITLE
Correct html file

### PR DESCRIPTION
**Pull request by fansub**
Based from #22

### CODE REVIEW

**Comment by fansub** [comment]
Missing:

- [ ] https://github.com/KasaiDot/fansub.github.io/commit/174f0d83f75f6b5cc69e523e9771880b32af1189
- [ ]  https://github.com/KasaiDot/fansub.github.io/commit/ac5c8fad81b3659ba79b53996f716bd546d5e216
- [ ] https://github.com/KasaiDot/fansub.github.io/commit/9ee649daee81c8d8d9edf5a97720bb0884d8fbe7
- [ ] https://github.com/KasaiDot/fansub.github.io/commit/9ac484032da60ec2f3a1c78c70f1c522993ebc4f
- [ ] https://github.com/KasaiDot/fansub.github.io/commit/48889b2a7a6e46a9a62534c19f74328ac795214e
- [ ] https://github.com/KasaiDot/fansub.github.io/commit/b685d493f475aba47a8a08ba0ac152856b90a5a9
- [ ] https://github.com/KasaiDot/fansub.github.io/commit/04f272d9538c84bb64afe2c8442e246277c2a1e2
- [ ] https://github.com/KasaiDot/fansub.github.io/commit/33af68b510dd423c13d91180e974dc26d79bd7d0
- [ ] https://github.com/KasaiDot/fansub.github.io/commit/e38631721521c7ea931d40ced962497dd788888f
- [ ] https://github.com/KasaiDot/fansub.github.io/commit/bef3de75f42ae8f0898e8c6cc002fe45c6e3cfec

**Comment by KasaiDot** [comment]
Je ne vois pas bien ce qu'il manque, mais je suis tout ouie ;D

**Comment by fansub** [comment]
It's for me, I just separate your PR #22 into #24 and #25 . And for this one, I've not finish to fix on my file some of your changes :)

**Comment by KasaiDot** [comment]
Oh, ok, je doit faire quelque chose de particulier, ou tout se passe de votre côté ?

**Pull request merged**
